-- AlterTable
ALTER TABLE "images" ALTER COLUMN "alt_text" DROP DEFAULT,
ALTER COLUMN "bucket_id" DROP DEFAULT,
ALTER COLUMN "height" DROP DEFAULT,
ALTER COLUMN "size" DROP DEFAULT,
ALTER COLUMN "type" DROP DEFAULT,
ALTER COLUMN "width" DROP DEFAULT;
